CREATE TABLE IF NOT EXISTS `gift_vouchers` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `order_id` bigint(20) unsigned NOT NULL,
    `cart_item_key` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
    `action_id` bigint(20) unsigned DEFAULT NULL,
    `code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `amount` decimal(15,4) NOT NULL,
    `buyer_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `buyer_email` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `recipient_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `recipient_email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
    `sender_name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `message` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
    `fulfilled_at` timestamp NULL DEFAULT NULL,
    `email_sent_at` timestamp NULL DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `gift_vouchers_code_unique` (`code`),
    UNIQUE KEY `gift_vouchers_order_id_cart_item_key_unique` (`order_id`,`cart_item_key`),
    KEY `gift_vouchers_order_id_index` (`order_id`),
    KEY `gift_vouchers_action_id_index` (`action_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
