CREATE TABLE IF NOT EXISTS `product_actions` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `title` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
    `type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
    `discount` decimal(15,4) NOT NULL DEFAULT 0.0000,
    `group` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
    `links` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `date_start` timestamp NULL DEFAULT NULL,
    `date_end` timestamp NULL DEFAULT NULL,
    `badge` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `min_cart` decimal(15,4) DEFAULT NULL,
    `data` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `coupon` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `quantity` tinyint(1) unsigned NOT NULL DEFAULT 0,
    `lock` tinyint(1) unsigned NOT NULL DEFAULT 0,
    `logged` tinyint(1) unsigned NOT NULL DEFAULT 0,
    `uses_customer` int(10) unsigned NOT NULL DEFAULT 1,
    `viewed` int(10) unsigned NOT NULL DEFAULT 0,
    `clicked` int(10) unsigned NOT NULL DEFAULT 0,
    `status` tinyint(1) unsigned NOT NULL DEFAULT 0,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `product_actions_group_index` (`group`),
    KEY `product_actions_status_index` (`status`),
    KEY `product_actions_coupon_index` (`coupon`),
    KEY `product_actions_group_status_index` (`group`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
