-- Znanje import tablice za live bazu (phpMyAdmin / MySQL 5.7+).
-- Skripta je idempotentna i ne zahtijeva pristup INFORMATION_SCHEMA bazi.

CREATE TABLE IF NOT EXISTS `znanje_import_feed_rows` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `feed_token` CHAR(36) NOT NULL,
    `external_id` VARCHAR(64) NOT NULL,
    `remote_product_id` BIGINT UNSIGNED NULL,
    `feed_position` INT UNSIGNED NULL,
    `name` VARCHAR(255) NOT NULL,
    `description` MEDIUMTEXT NULL,
    `source_category` VARCHAR(191) NULL,
    `source_categories` JSON NULL,
    `source_publisher` VARCHAR(191) NULL,
    `source_url` VARCHAR(1024) NOT NULL,
    `image_url` VARCHAR(1024) NULL,
    `additional_image_urls` JSON NULL,
    `price_eur` DECIMAL(15,4) NOT NULL DEFAULT 0,
    `sale_price_eur` DECIMAL(15,4) NULL,
    `availability` VARCHAR(32) NULL,
    `sku` VARCHAR(191) NULL,
    `isbn` VARCHAR(32) NULL,
    `ean` VARCHAR(32) NULL,
    `author` VARCHAR(255) NULL,
    `source_genres` JSON NULL,
    `genre` VARCHAR(255) NULL,
    `format` VARCHAR(128) NULL,
    `pages` INT UNSIGNED NULL,
    `letter` VARCHAR(64) NULL,
    `binding` VARCHAR(64) NULL,
    `publication_year` SMALLINT UNSIGNED NULL,
    `language` VARCHAR(64) NULL,
    `origin` VARCHAR(128) NULL,
    `source_hash` CHAR(64) NOT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `znanje_feed_rows_token_external_unique` (`feed_token`, `external_id`),
    KEY `znanje_import_feed_rows_feed_token_index` (`feed_token`),
    KEY `znanje_feed_rows_token_remote_index` (`feed_token`, `remote_product_id`),
    KEY `znanje_feed_rows_created_at_index` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `znanje_import_products` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `external_id` VARCHAR(64) NOT NULL,
    `remote_product_id` BIGINT UNSIGNED NULL,
    `feed_position` INT UNSIGNED NULL,
    `product_id` BIGINT UNSIGNED NULL,
    `name` VARCHAR(255) NOT NULL,
    `description` MEDIUMTEXT NULL,
    `source_category` VARCHAR(191) NULL,
    `source_categories` JSON NULL,
    `source_publisher` VARCHAR(191) NULL,
    `source_url` VARCHAR(1024) NOT NULL,
    `image_url` VARCHAR(1024) NULL,
    `additional_image_urls` JSON NULL,
    `price_eur` DECIMAL(15,4) NOT NULL DEFAULT 0,
    `sale_price_eur` DECIMAL(15,4) NULL,
    `availability` VARCHAR(32) NULL,
    `sku` VARCHAR(191) NULL,
    `isbn` VARCHAR(32) NULL,
    `ean` VARCHAR(32) NULL,
    `author` VARCHAR(255) NULL,
    `source_genres` JSON NULL,
    `genre` VARCHAR(255) NULL,
    `format` VARCHAR(128) NULL,
    `pages` INT UNSIGNED NULL,
    `letter` VARCHAR(64) NULL,
    `binding` VARCHAR(64) NULL,
    `publication_year` SMALLINT UNSIGNED NULL,
    `language` VARCHAR(64) NULL,
    `origin` VARCHAR(128) NULL,
    `detail_payload` JSON NULL,
    `source_hash` CHAR(64) NOT NULL,
    `checked_source_hash` CHAR(64) NULL,
    `imported_hash` CHAR(64) NULL,
    `feed_token` CHAR(36) NOT NULL,
    `is_current` TINYINT(1) NOT NULL DEFAULT 0,
    `check_status` VARCHAR(32) NOT NULL DEFAULT 'pending',
    `check_message` TEXT NULL,
    `checked_at` TIMESTAMP NULL DEFAULT NULL,
    `last_seen_at` TIMESTAMP NULL DEFAULT NULL,
    `imported_at` TIMESTAMP NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `znanje_import_products_external_id_unique` (`external_id`),
    UNIQUE KEY `znanje_import_products_remote_product_id_unique` (`remote_product_id`),
    KEY `znanje_import_products_feed_position_index` (`feed_position`),
    KEY `znanje_import_products_product_id_index` (`product_id`),
    KEY `znanje_import_products_source_category_index` (`source_category`),
    KEY `znanje_import_products_source_publisher_index` (`source_publisher`),
    KEY `znanje_import_products_availability_index` (`availability`),
    KEY `znanje_import_products_sku_index` (`sku`),
    KEY `znanje_import_products_isbn_index` (`isbn`),
    KEY `znanje_import_products_ean_index` (`ean`),
    KEY `znanje_import_products_feed_token_index` (`feed_token`),
    KEY `znanje_import_products_is_current_index` (`is_current`),
    KEY `znanje_import_products_check_status_index` (`check_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SHOW TABLES LIKE 'znanje_import_feed_rows';
SHOW TABLES LIKE 'znanje_import_products';

-- Brza provjera po EAN-u koristi indeks iz database/069_add_products_ean_index.sql.
SHOW INDEX FROM `products` WHERE `Key_name` = 'products_ean_index';
